version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file /iac/template.yaml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-oww4c3mqhsxf --output-template-file /iac/outputTemplate.yaml
artifacts:
  type: zip
  files:
    - /iac/template.yaml
    - /iac/outputTemplate.yaml